controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      wheel_separation: 0.04
      wheel_radius: 0.115
      use_stamped_vel: false
      base_frame_id: base_link
      cmd_vel_timeout: 0.25
      publish_rate: 50
